Feature/questions views
4u3o/test-guru pull request #11
Opened 2023-09-21 12:52 UTC by 4u3o

2023-09-21 16:59 UTC, BubuntuClu requested changes

2023-09-21 16:59 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.required(:question).permit(:body,
нестед атрибуты в этом курсе не будут рассматриваться. тут хватит параметро только для вопроса

2023-09-21 16:59 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    {'new' => "Create #{test_title_question}",
лучше завязаться на состоянии объекта, а не на имени экшена. вдруг тебе в другом экшене тоже надо будет вывести подобный заговловок.
используй `new_record?/persisted?` методы чтобы определить какой заголовок использовать

2023-09-21 16:59 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @tests = Test.joins(:questions)
а зачем так сложно? почему не `Test.all` и потом `test.questions.size`

если ты хочешь избежать N+1, то это достигается другими методами `includes/preload/eager_load`. в рельсе этот способ применяется, а не через добавление доп "виртуальной" колонки к объекту модели

2023-09-21 21:26 UTC, 4u3o commented on app/controllers/tests_controller.rb
> +    @tests = Test.joins(:questions)
Стоит ли тащить все вопросы из БД, если нам нужно только их количество?

2023-09-22 06:59 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @tests = Test.joins(:questions)
в таких случаях обычно делают манипуляции с кэшом, чтобы не делать доп запросы. в данном случае мы еще с кэшом не знакомы, изучаем различные инструменты как в принципе можно это сделать. всякие оптимизации за рамками курса/в след курсе

2023-09-22 07:06 UTC, merged