Feature/models validations
4u3o/test-guru pull request #8
Opened 2023-09-13 10:34 UTC by 4u3o

2023-09-13 17:16 UTC, BubuntuClu requested changes

2023-09-13 17:16 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_answers_count
в какой момент срабатывает валидация в модели? когда мы объект создаем или обновляем. если мы будем создавать объект ответа, валидация в вопросе будет работать?

2023-09-13 17:16 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add(:answers, "must be from #{MIN_ANSWERS} to #{MAX_ANSWERS}") unless
1 - минимальное значение проверять не надо. даже не знаю как это должно работать, ес честно
2 - старайся писать условия через `if`, так как он воспринимается легче при чтении

2023-09-13 17:16 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :titles_by_category, -> (title) do
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2023-09-14 07:13 UTC, 4u3o commented on app/models/question.rb
> +  def validate_answers_count
намек понял

2023-09-14 08:22 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:answers, "must be no more than #{Question::MAX_ANSWERS}") if
стоит ли лезть за константой в другой класс?
может в этом же классе объявить ее? та константа в самом вопросе не используется и как будто выглядит в нем лишней

2023-09-14 08:44 UTC, merged